name: Set environment variables
on: [push]
env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  trying-to-use-environment-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          echo ${{ secrets.API_KEY }}
          echo "API_KEY=${{ secrets.API_KEY }}"
